version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=masterkey
      - MEILI_LOG_LEVEL=info
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  meilisearch_data:
    driver: local
